version: '3'
services:
  app:
    build: .
    restart: always
    links:
      - postgres
    networks:
      - int_net
      - ext_net
  postgres:
    image: postgres:15.3-bullseye
    networks:
      - int_net
    environment:
      - POSTGRES_DB=yamag
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
networks:
  int_net:
    internal: true
  ext_net:
    
