version: '3'
services:
  app:
    build: .
    restart: always
    links:
      - db
    networks:
      - int_net
      - ext_net
    env_file:
      - .env.app
  db:
    image: postgres:15.3-bullseye
    networks:
      - int_net
    env_file:
      - .env.db
    volumes:
      - ./data:/var/lib/postgresql/data
networks:
  int_net:
    internal: true
  ext_net:
